apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "30"]
          volumeMounts:
            - name: nginx-config-vol
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: {{ .Values.nginx.healthPath }}
              port: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.nginx.healthPath }}
              port: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: nginx-config-vol
          configMap:
            name: nginx-config
